name: Spark Iceberg image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker tag to apply to this image'
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: tabulario
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        if: ${{ github.ref_name == 'main' }}
        env:
          IMAGE_TAG: ${{ inputs.tag }}
        with:
          context: spark/
          file: spark/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tabulario/spark-iceberg:latest,tabulario/spark-iceberg:${{ inputs.tag }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        if: ${{ github.ref_name != 'main' }}
        env:
          IMAGE_TAG: ${{ inputs.tag }}
        with:
          context: spark/
          file: spark/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tabulario/spark-iceberg:${{ inputs.tag }}
